import './bootstrap';
import './components/cookie-modal';
import './components/form';
import './components/map';
import './components/modal';
import './components/navmenu';
import './components/phone-mask';
import './components/pulse-button';
import './components/slider';